### ISSUE TITLE
Build linux kernel 5.X to LLVM IR

### ISSUE THREAD

**Issue by bsauce** [ClangBuiltLinux/dockerimage#27] opened 2019-06-10 02:21 UTC
For now, Linux kernel has been updated to 5.X. I want to compile whole 5.0 kernel to bitcode file. How could I achieve this by using ClangBuilt Linux? Is there any advice? Thanks for your advice.

**Comment by nickdesaulniers** [comment] 2019-06-10 20:10
duplicate of https://github.com/ClangBuiltLinux/linux/issues/513

**Closed by nickdesaulniers** 2019-06-10 20:10 UTC
